### ISSUE TITLE
Does Multiverse works for BukkitForge?

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#473] opened 2013-02-08 17:35 UTC
I read that it would be buggy, but working for BukkitForge, but I remember, it was a few weeks ago, i really can't create, import oder tp me to another world!!
And I need the possibility to switch between worlds! Does it works?

**Comment by EDSman11** [comment] 2013-02-08 22:42
I don't think so I couldn't get it to load in the first place...

**Comment by eagl3s1ght** [comment] 2013-02-08 23:43
No.

**Comment by ghost** [comment] 2013-02-09 10:22
Is there an alternative for world switching?

**Comment by Ionaru** [comment] 2013-02-09 11:03
MultiWorld

**Comment by mmis1000** [comment] 2013-02-09 18:12
though worldgen seems fixed(regions in the save folder looks fine,and no crash when trying to create a bukkit world)
The bukkitforge seems crash the mc when players trying to enter a bukkit world
may be the last several issue until bukkit world works I though

**Comment by DerpgonCz** [comment] 2013-02-10 10:49
It works for me

**Comment by Sageavatar** [comment] 2013-02-10 16:02
DragonCzz, would you please provide us with your Bukkitforge build number asw well as a list of plugins? thanks.

**Comment by DerpgonCz** [comment] 2013-02-10 19:07
MultiVerse: http://dev.bukkit.org/server-mods/multiverse-core/files/23-2-4-ab/
BukkitForge: http://build.technicpack.net/job/BukkitForge/227/

Well, permissions does not work, because it is currently broken in BukkitForge (even GroupManager did not help me)
EDIT: I found out that more world does not work either, but MV Portals works :dancers:

**Comment by eagl3s1ght** [comment] 2013-02-12 07:31
So what, Multiverse-Portals work, but not Multiverse Core? I am getting this error on loading Multiverse-Core. How are you able to get just Multiverse-Portals to work?

```
2013-02-12 07:51:49 [SEVERE] [BukkitForge] Error occurred while enabling Multiverse-Core v2.4-b527 (Is it up to date?)
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.util.ArrayList$Itr.next(Unknown Source)
    at org.bukkit.craftbukkit.CraftWorld.getPlayers(CraftWorld.java:786)
    at com.onarandombox.MultiverseCore.MVWorld.setActualGameMode(MVWorld.java:915)
    at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:225)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:150)
    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:91)
    at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:557)
    at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:242)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:426)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:838)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:822)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:235)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)
    at java.lang.Thread.run(Unknown Source)
```

And then somehow I am able to get an EventException:

```
2013-02-12 08:20:08 [SEVERE] [BukkitForge] Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:393)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java)
    at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:417)
    at com.earth2me.essentials.Teleport.now(Teleport.java:244)
    at com.earth2me.essentials.Teleport.teleport(Teleport.java:277)
    at com.earth2me.essentials.Teleport.teleport(Teleport.java:257)
    at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:58)
    at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:38)
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:96)
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:407)
    at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:70)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b_net_minecraft_network_NetworkListenThread_networkTick_p0(NetworkListenThread.java:57)
    at iw.b(NetworkListenThread.java)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:259)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:176)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:104)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerTeleport(MVPlayerListener.java:198)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
    ... 28 more
```

**Comment by Sageavatar** [comment] 2013-02-12 08:44
@DragonCzz So MV Portals works for you. What in Core works? Generation? Import? Teleportation? I see the versions you are using. Any other relevant plugins? Thanks.(Groupmanager works for me. It didn't used to, but it does now. Using latest.)

**Comment by DerpgonCz** [comment] 2013-02-12 10:09
Well, Core loads correctly, but /mv create not as I found out later. TPing works

**Comment by mmis1000** [comment] 2013-02-12 14:06
mw loads fine and, create world also works fine ,but go to mw world=crash

**Comment by ghost** [comment] 2013-02-12 16:20
but teleport is the main thing

**Comment by DerpgonCz** [comment] 2013-02-12 17:14
World creating does not work for me, but TPing works :D

**Comment by Sageavatar** [comment] 2013-02-12 17:46
So the question is why would gen works for some of us and other's it does not. While others TPing works and for others it crashes (the server I'm assuming.) So what's the differences we have? Possibly we have conflicting plugins? It does not makes sense that some of us can do one or the other but not both.

(I won't list my versions as I have not tested since BF # 185 or so)

**Comment by DerpgonCz** [comment] 2013-02-12 17:50
As I commented before, these version works together to allow TPing. I tried without any mods / plugins. Maybe someone can have fighting plguins or mods. Maybe other versions of BF (I update is every day if theres a new update)

**Comment by SpoonsJTD** [comment] 2013-02-12 18:42
Gen does not work, period. Just because it says the world was created, it doesn't mean it was generated. TP'ing to and from forge worlds should work. TP'ing to a bukkit created world is typically what kicks off the actual generation of the world, which will fail and is why it seems like TP doesnt work. The TP is successful, it's the gen that fails. This is bad, because the player will be stuck with a position inside a ungeneratable world, so every time that player joins, it will blow up.

**Comment by eagl3s1ght** [comment] 2013-02-13 20:52
@DragonCzz, why are you running Bukkitforge without any mods? _curious_

**Comment by DerpgonCz** [comment] 2013-02-13 21:11
@eagl3s1ght I tried to run BF without any mods, just to check if it is not interfering wit any plugin or mod

**Comment by eagl3s1ght** [comment] 2013-02-13 22:23
@Dragonczz, the interesting thing is to know if it works with any mods. Did you get that working? If yes, how did you import the world? Did you repair it with Chunkster?

**Comment by DerpgonCz** [comment] 2013-02-14 17:04
Well, only TPing worked, world generation does not work for me for some strange reason (even Nether o The End or any dimensions via MystCraft)

**Comment by EDSman11** [comment] 2013-02-14 19:47
what if you added a pre-generaterated (a single-player world) world folder
into the main server directory then did /mw create <world name> to load it?
Would it work then since it isn't having to generate it its just loading it?

**Comment by eagl3s1ght** [comment] 2013-02-15 14:24
@EDSman11, I tried this, by using the import feature of Multiverse. Didn't work, probably because Multiverse doesn't like that there's mod items in the map (might work without, didn't test that- but who are we kidding, mod ore generation is the fun.)

**Comment by EDSman11** [comment] 2013-02-15 18:02
I was talking about using multiworld for importing because multiworld seems
to b having more success than multiverse currently... The only problem with
multiworld is generation of the world wich is what i am attempting to
bypass by loading a pre-gened world through multiworld...

**Comment by SpoonsJTD** [comment] 2013-02-28 02:00
Multiverse doesn't recognize worlds because it assumes the world folder is named the same as the world. I have an open issue with the multiverse project. This whole thread is a dupe of #138 et all.

**Closed as completed by SpoonsJTD** 2013-02-28 02:00 UTC
