### ISSUE TITLE
[Permissions] Permisssions again

### ISSUE THREAD

**Issue by Tory05** [keepcalm/BukkitForge#34] opened 2012-12-20 15:01 UTC
I retried the permissions, with pex but still same error...

**Comment by Thornas88** [comment] 2012-12-20 16:14
post your log. ^^

**Comment by Tory05** [comment] 2012-12-20 17:08
Same issue as "[PermissionsEx bug?] Permissions are ignored."
The log is clean, no errors..
I'm op but cant use commands.

**Comment by Thornas88** [comment] 2012-12-20 18:09
show this https://github.com/keepcalm/BukkitForge/issues/31

**Comment by keepcalm** [comment] 2012-12-20 22:57
Ok. I think it's a problem with my command code, but I will try to fix it. Again.

**Comment by SpoonsJTD** [comment] 2013-01-18 20:40
Going to leave this as the current 'Permissions' issue and dupe others. It appears that permission plugins can save permissions, but when hasPermissions is called, the permission check fails regardless of whether player has the assigned permissions or not, except for admins.

**Comment by SpoonsJTD** [comment] 2013-01-19 01:11
Actually, #212 seems to capture the issue better, will close this one as dupe of it.

**Closed as completed by SpoonsJTD** 2013-01-19 01:11 UTC
