### ISSUE TITLE
World Guard,and all another plugin's cant block explosion event

### ISSUE THREAD

**Issue by fhntv24** [keepcalm/BukkitForge#485] opened 2013-02-10 17:34 UTC
World Guard,and all another plugin's cant block explosion event

**Comment by DerpgonCz** [comment] 2013-02-10 19:04
Same issue here, had to turn off monsters, deny placing of TNT all all other Explosives. It is very hard to make a good FML server with plugins and make it playable

**Comment by fhntv24** [comment] 2013-02-11 14:06
i know)

**Comment by BushTrocity** [comment] 2013-02-11 18:46
Essentials can do creeper i know of. I don't know about tnt, i don't have that off on my server.

**Comment by fhntv24** [comment] 2013-02-11 19:47
? can do what? block creeper exp.? how? if you about block private,it's not that

**Comment by BushTrocity** [comment] 2013-02-11 19:52
essentials protect near the bottom of the congfig file just set it to true to block creeper block dmg.

**Comment by ghost** [comment] 2013-02-12 19:52
Neither one of these plugins event blockers are working for me. This includes creepers, banning items, fire spread, explosions, ect....

**Comment by BushTrocity** [comment] 2013-02-12 20:02
I guess it works for some people and others it doesn't. Because creepers don't do block damage on my server. But fire spread still happens for me. Just have to wait for it to be fixed.

**Comment by fhntv24** [comment] 2013-02-14 06:16
But fire spread still happens for me. Just have to wait for it to be fixed.
you can turn it off,
essentials protect near the bottom of the congfig file just set it to true to block creeper block dmg.
oh really? for me it's not _blowing up all world with command nuke_
banning items
lol...that is not event....like crafting it's not event...i think

**Comment by SpoonsJTD** [comment] 2013-02-28 02:43
Dupe of multiple creeper/fire spread issues.

**Closed as completed by SpoonsJTD** 2013-02-28 02:43 UTC
