### ISSUE TITLE
Griefprevention golden shovel click events

### ISSUE THREAD

**Issue by Lightforger** [keepcalm/BukkitForge#226] opened 2013-01-12 20:55 UTC
bukkitforge build21 (technic) - Griefprevention 7.2.1

Placing down a chest creates a well-working protection.
Clicking with a golden shovel in a new world with all default settings -> 1 corner of the claim is already locked to x/y 0,0.
Seems to not relay the "first click for corner 1, 2nd click for other corner".

No errors.

**Comment by MatadorPants** [comment] 2013-01-16 00:45
GriefPrevention doesn't seem to work much for me either. 

It randomly will create a claim correctly, but most of the time spams messages that may or may not be related to what you're trying to do. 

For instance, if you get it to successfully create a claim, it'll say "Claim created" and then it'll post a second message saying "Claim corner set! Use the shovel again at the opposite corner"

I'm not sure how to explain the issues it's having, but you're welcome to join the server and see for yourself.

It does seem to be locked to 0,0 as the first commenter said. When I try to create a new plot, it acts as if a corner is already set at 0,0.

**Comment by SpoonsJTD** [comment] 2013-01-19 01:24
Seems dupe of #78

**Closed as completed by SpoonsJTD** 2013-01-19 01:24 UTC
