### ISSUE TITLE
Crash after startup finished

### ISSUE THREAD

**Issue by Tory05** [keepcalm/BukkitForge#8] opened 2012-12-10 00:27 UTC
I have a problem after server starts up:

 http://pastebin.com/k7SsE06G

Using mods : bukkit4vanilla-1.4.5-0; Dynmap-1.2(forge); More Swords Mod 2.1.3
Using plugins : Essentials-2.9 (port)

**Comment by keepcalm** [comment] 2012-12-10 01:13
Dupe of #3, fixed already

**Closed as completed by keepcalm** 2012-12-10 01:13 UTC
