### ISSUE TITLE
[LWC][b107] NoClassDefFoundError: JSONParser

### ISSUE THREAD

**Issue by lihad** [keepcalm/BukkitForge#365] opened 2013-01-25 09:25 UTC
LWC does use simple-json I believe, but Im picking up this exception on startup.

2013-01-25 01:15:07 [SEVERE] [BukkitForge] Error occurred while enabling LWC v1.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/json/simple/parser/JSONParser
    at com.griefcraft.sql.PhysDB.<init>(PhysDB.java:57)
    at com.griefcraft.lwc.LWC.load(LWC.java:1421)
    at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:231)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:379)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugin(BukkitServer.java:935)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.enablePlugins(BukkitServer.java:919)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:243)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:46)

**Comment by SpoonsJTD** [comment] 2013-01-25 14:39
Dupe of #134, please search before posting issues.

**Closed as completed by SpoonsJTD** 2013-01-25 14:39 UTC
