### ISSUE TITLE
Crash on Load. Issue with Mod Compatibility

### ISSUE THREAD

**Issue by thelapisfox** [keepcalm/BukkitForge#97] opened 2013-01-03 11:52 UTC
http://pastebin.com/mteMLA5F and http://pastebin.com/ut0XXw34

Those should help you with figuring this out. I am pretty sure, after looking over the error myself, that is it a compatibility issue with the Forge mod, Xycraft. Not completely sure the exact reason for this, but I am sure you will figure it out.

Also, so you know, I use the launcher from Feed-The-Beast and I use DireWolf20's Mod Pack from there.

**Comment by keepcalm** [comment] 2013-01-03 12:28
Duplicate of #96 - looks like I forgot to change the size of an array...

**Closed as completed by keepcalm** 2013-01-03 12:28 UTC
Labels: status - duplicate
