### ISSUE TITLE
[Crash report] No enum constant org.bukkit.event.entity.EntityDamageEvent.DamageCause.onFire

### ISSUE THREAD

**Issue by ariaththewise** [keepcalm/BukkitForge#7] opened 2012-12-09 17:07 UTC
Complete crash report: http://pastebin.com/wDrJVdYv

See ya and thanks for your efforts :) !

**Comment by keepcalm** [comment] 2012-12-10 01:14
Dupe of #1, fixed.

**Closed as completed by keepcalm** 2012-12-10 01:14 UTC
