### ISSUE TITLE
[Essentials] Signs

### ISSUE THREAD

**Issue by BrockWS** [keepcalm/BukkitForge#501] opened 2013-02-13 05:39 UTC
When ever i try to use essentials signs ([Gamemode], &5This is purple) it changes to !?. I have enabled the signs in the config. and i only have essentials core plugins installed. It works fine with craftbukkit

**Comment by eagl3s1ght** [comment] 2013-02-13 13:06
I have noticed this happens with ChestShop.
Are you sure it is not fixed after relog?

**Comment by BrockWS** [comment] 2013-02-13 13:27
I only have essentials installed and no it does get fixed

**Comment by Sageavatar** [comment] 2013-02-13 17:31
This is a duplicate of #213

**Comment by SpoonsJTD** [comment] 2013-02-28 03:06
Signs are fixed except for Buy/Sell/Trade, captured in a another issue.

**Closed as completed by SpoonsJTD** 2013-02-28 03:06 UTC
