### ISSUE TITLE
Could not load JSONAPI 

### ISSUE THREAD

**Issue by mafen** [keepcalm/BukkitForge#250] opened 2013-01-14 21:40 UTC
2013-01-14 22:32:13 [SEVERE] [BukkitForge] Could not load './plugins/JSONAPI.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:908)
    at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.<init>(BukkitServer.java:269)
    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_6.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 9 more
2013-01-14 22:32

http://forums.bukkit.org/threads/admn-info-jsonapi-v4-1-0-json-http-and-socket-api-for-controlling-a-server-1-4-6.14270/¨

**Comment by taylorberg** [comment] 2013-01-17 01:37
It's because it's trying to access a class in net.minecraft.server, which, if i recall correctly, isn't in BukkitForge. Any chance we could get some official support for this plugin?

**Comment by Manawyrm** [comment] 2013-01-17 15:01
I do not think we could get official support anytime soon... 
But -- JSONApi is a great and open source piece of software. 
Chances are, somebody tries to build up a different JSONApi version.

**Comment by SpoonsJTD** [comment] 2013-01-19 01:31
Dupe of #135

**Closed as completed by SpoonsJTD** 2013-01-19 01:31 UTC

**Comment by Manawyrm** [comment] 2013-02-17 15:46
Problem fixed with custom build of JSONApi:
https://github.com/Manawyrm/jsonapi

**Comment by alecgorge** [comment] 2013-02-22 20:28
This is fixed in JSONAPI v4.3.0
