### ISSUE TITLE
[WorldEdit] id's > 255

### ISSUE THREAD

**Issue by hanspaerna** [keepcalm/BukkitForge#317] opened 2013-01-21 19:37 UTC
Hi. I have a strange problem with ForgeBukkit and WorldEdit (tried all latest versions): blocks with id > 255 (non-byte) don't work with WE copy/paste, stack or schematic saving. I also don't have any error in logs. WorldEdit just doesn't see them. In 1.2.5 non-FB version everything worked good. It's only my problem or not?

**Comment by kozlek** [comment] 2013-01-21 20:38
Yes, I have the same problem (issue #312 ) :-(
At least I think this was a problem about custom block, but in fact it only happens when block are up to 255.

**Comment by keepcalm** [comment] 2013-01-21 22:36
Are you on 1.4.6 or 1.4.7?

**Comment by joey19982** [comment] 2013-01-21 22:36
Same issue here. D:

**Comment by hanspaerna** [comment] 2013-01-22 00:21
I'm using 1.4.6 Minecraft version.

**Comment by kozlek** [comment] 2013-01-22 06:04
For me it happens with forge #497 and minecraft 1.4.7

**Comment by kozlek** [comment] 2013-01-22 18:33
I try the old (patched I think) version of worldedit and it works :-)
![worldedit-5 4 5](https://f.cloud.github.com/assets/3019422/87448/2ed480e4-64c2-11e2-80eb-38571cbd3673.png)

Just click on the image -> save as -> rename the file extension to .zip

**Comment by hanspaerna** [comment] 2013-01-22 21:53
Thanks, but it doesn't work with RedPower 2 microblocks (officially it should). Does anyone have the same problem?

**Comment by mmis1000** [comment] 2013-01-23 05:12
I have the same problem too
seems It was caused by the auto patcher in bukkitforge or worldedit itself.
I think it is much like caused by the auto patcher in bukkitforge
Since the old patched one can read the ids above 255 normally
But the new auto patched one can't
And I also haven't found any one on the worldedit forum has the same problem

**Comment by kozlek** [comment] 2013-01-23 17:08
Me too :-(

**Comment by SirKnightBJ** [comment] 2013-01-31 05:06
Haha, I'm having the same problem. Did we come up with a fix for this issue? With 8 days on the last post, thats the way it looks..  and it appears that I have missed it. I guess I'm not grasping what Tberdy had meant when they said,

"I try the old (patched I think) version of worldedit and it works :-)
Just click on the image -> save as -> rename the file extension to .zip"

Where would I find this old patched version of W.E.?

p.s. I'm running Bukkitforge on my FTB MindCrack server, Any idea if the latest FTB update will affect the performance of the current BukkitForge version 187?

**Comment by keepcalm** [comment] 2013-01-31 21:35
@bjj89us, it shouldn't. Use WE 5.5 (normal), and make sure you unzip it.

**Closed as completed by keepcalm** 2013-01-31 21:35 UTC

**Comment by SirKnightBJ** [comment] 2013-02-01 03:30
Success!! Thank you Keepcalm! You Guys are doing great work :D!

**Comment by kozlek** [comment] 2013-02-02 16:30
I tried with WE 5.5.1 and BF #199 but it still doesnt work. 
Moreover, I had some log error :
2013-02-02 17:22:35 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS access for direct NBT data copy
java.lang.NullPointerException
    at com.sk89q.worldedit.bukkit.BukkitWorld.getBlock(BukkitWorld.java:1311)
    at com.sk89q.worldedit.EditSession.rawGetBlock(EditSession.java:407)
    at com.sk89q.worldedit.EditSession.getBlock(EditSession.java:361)
    at com.sk89q.worldedit.EditSession.setBlock(EditSession.java:258)
    at com.sk89q.worldedit.EditSession.setBlocks(EditSession.java:1151)
    at com.sk89q.worldedit.commands.RegionCommands.set(RegionCommands.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:257)
    at com.sk89q.worldedit.WorldEdit$1.invokeMethod(WorldEdit.java:1)
    at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
    at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:425)
    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1394)
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-02-02 17:22:35 [WARNING] [Minecraft.WorldEdit] WorldEdit: Failed to do NMS safe block set
java.lang.NullPointerException
    at com.sk89q.worldedit.bukkit.BukkitWorld.setBlock(BukkitWorld.java:1330)
    at com.sk89q.worldedit.EditSession.rawSetBlock(EditSession.java:237)
    at com.sk89q.worldedit.EditSession.flushQueue(EditSession.java:707)
    at com.sk89q.worldedit.WorldEdit.handleCommand(WorldEdit.java:1409)
    at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:247)
    at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:52)
    at keepcalm.mods.bukkit.forgeHandler.commands.CommandExecutor2CommandBase.b(CommandExecutor2CommandBase.java:105)
    at x.a(CommandHandler.java:82)
    at iv.d(NetServerHandler.java:768)
    at iv.a(NetServerHandler.java:734)
    at cu.a(SourceFile:44)
    at cg.b(TcpConnection.java:458)
    at iv.d(NetServerHandler.java:136)
    at iw.b(NetworkListenThread.java:57)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
    at ho.r(DedicatedServer.java:269)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)

**Comment by SirKnightBJ** [comment] 2013-02-02 22:34
5.5 not 5.5.1...
