### ISSUE TITLE
permissions not working?

### ISSUE THREAD

**Issue by Bucky420** [keepcalm/BukkitForge#131] opened 2013-01-06 07:46 UTC
umm if any one can confirm pex or group manager working  

permissions like -worledit.\* or - '*' are't working

i running this on tekkit lite

**Comment by TempestCraft** [comment] 2013-01-06 08:46
Pex does not work. Use group manager.

**Comment by ghost** [comment] 2013-01-06 09:04
Pex is working fine with me, But try using group manager.

**Comment by Benet** [comment] 2013-01-06 18:30
I can confirm this. I am using build 63. I tried pex, group manager and permissionsbukkit and none of them worked.

**Comment by ghost** [comment] 2013-01-07 05:08
so far build build 63 and just now 66 i have gotten pex to work much better than groupmanager, thanks to hypno

**Comment by keepcalm** [comment] 2013-01-07 05:29
OK, try using the PEX jar in the dist/ folder for now. I'm working on integrating BukkitForge support into vanilla PEX.

**Comment by SpoonsJTD** [comment] 2013-01-18 22:57
Closing as dupe - permissions issue.

**Closed as completed by SpoonsJTD** 2013-01-18 22:57 UTC
Labels: status - duplicate
