### ISSUE TITLE
AuthMe Inventory not being protected

### ISSUE THREAD

**Issue by ruifung** [keepcalm/BukkitForge#366] opened 2013-01-25 09:37 UTC
Caused by: java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setArmorContents(BukkitInventoryPlayer.java:59)
    at uk.org.whoami.authme.api.API.setPlayerInventory(API.java:170)
    at uk.org.whoami.authme.listener.AuthMePlayerListener.onPlayerQuit(AuthMePlayerListener.java:712)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:344)

**Comment by SpoonsJTD** [comment] 2013-01-25 14:37
Dupe of  #273

**Closed as completed by SpoonsJTD** 2013-01-25 14:37 UTC

**Comment by ruifung** [comment] 2013-01-26 12:55
Oops. My bad, forgot about that.
