### ISSUE TITLE
[xAuth]

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#305] opened 2013-01-21 08:14 UTC
player can register, login, but before registration can move, etc. NPE:

2013-01-21 09:09:24 [INFO] [Minecraft] HunterzCZ[/137.0.0.8:37057] logged in with entity id 124 at (61.19635301327123, 66.0, 7.154970945716322)
2013-01-21 09:09:24 [INFO] [STDOUT] Found an applicable injector: keepcalm.mods.bukkit.bukkitAPIentity.CraftHumanEntity
2013-01-21 09:09:24 [WARNING] [Minecraft] [PermissionsEx] Unknown server implementation being used!
2013-01-21 09:09:24 [SEVERE] [BukkitForge] Could not pass event PlayerLoginEvent to xAuth v2.0.26
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:390)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:137)
    at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
    at gm.a(ServerConfigurationManager.java:143)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.cypherx.xauth.listeners.xAuthPlayerListener.onPlayerLogin(xAuthPlayerListener.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:388)
    ... 19 more
2013-01-21 09:09:24 [INFO] [STDOUT] Found an applicable injector: keepcalm.mods.bukkit.bukkitAPIentity.CraftHumanEntity
2013-01-21 09:09:24 [WARNING] [Minecraft] [PermissionsEx] Unknown server implementation being used!
2013-01-21 09:09:24 [SEVERE] [BukkitForge] Could not pass event PlayerLoginEvent to xAuth v2.0.26
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:390)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.playerLoggedIn(ConnectionHandler.java:137)
    at cpw.mods.fml.common.network.NetworkRegistry.playerLoggedIn(NetworkRegistry.java:161)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePlayerLogin(FMLNetworkHandler.java:281)
    at gm.a(ServerConfigurationManager.java:143)
    at it.completeConnection(NetLoginHandler.java:195)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:153)
    at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
    at it.d(NetLoginHandler.java:179)
    at it.c(NetLoginHandler.java:72)
    at hu.a(ServerListenThread.java:56)
    at ht.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
    at ho.r(DedicatedServer.java:270)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.cypherx.xauth.listeners.xAuthPlayerListener.onPlayerLogin(xAuthPlayerListener.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:388)
    ... 19 more
2013-01-21 09:09:24 [INFO] [STDOUT] [UltraBan] Logged HunterzCZ connecting from ip:137.0.0.8
2013-01-21 09:09:24 [INFO] [STDOUT] Whitelist: Player HunterzCZ is trying to join...allow!
2013-01-21 09:09:24 [WARNING] [BukkitForge] Task #18 for xAuth v2.0.26 generated an exception
java.lang.NullPointerException
    at keepcalm.mods.bukkit.bukkitAPI.inventory.BukkitInventoryPlayer.setHelmet(BukkitInventoryPlayer.java:66)
    at com.cypherx.xauth.PlayerDataHandler.storeData(PlayerDataHandler.java:73)
    at com.cypherx.xauth.PlayerManager.protect(PlayerManager.java:230)
    at com.cypherx.xauth.listeners.xAuthPlayerListener$1.run(xAuthPlayerListener.java:335)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VTask.run(B4VTask.java:53)
    at keepcalm.mods.bukkit.bukkitAPI.scheduler.B4VScheduler.mainThreadHeartbeat(B4VScheduler.java:347)
    at keepcalm.mods.bukkit.forgeHandler.SchedulerTickHandler.tickStart(SchedulerTickHandler.java:38)
    at cpw.mods.fml.common.SingleIntervalHandler.tickStart(SingleIntervalHandler.java:16)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:119)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
    at fy.run(SourceFile:849)
2013-01-21 09:10:12 [INFO] [BukkitForge] HunterzCZ issued server command: loginsecretpassword
2013-01-21 09:10:12 [INFO] [BukkitForge.xAuth] [xAuth] HunterzCZ authenticated

**Comment by ruifung** [comment] 2013-01-21 09:51
Duplicate of #273.

**Comment by SpoonsJTD** [comment] 2013-01-21 17:25
Closing as dupe.

**Closed as completed by SpoonsJTD** 2013-01-21 17:25 UTC
