### ISSUE TITLE
Coreprotect, bkcommonlib, Nolagg

### ISSUE THREAD

**Issue by Flouzr** [keepcalm/BukkitForge#144] opened 2013-01-06 22:06 UTC
coreprotect doesnt work, it fails when you rollback at file 4/9.

bkcommonlib doesnt work/load becuase it recognizes that it is not craftbukkit.

nolagg doesnt work because it requites bkcommonlib to load.

i cant provide errors because for some reason i cant launch the server. will post back when i can.

Here is the pastebin: http://pastebin.com/XRi0a78j

Even though it says nolagg is enabled it is not.    /nolagg in console & ingame does nothing

**Comment by Erycus** [comment] 2013-01-07 01:03
I believe that I read somewhere nolagg will not work...you could try looking at clearlag perhaps.
http://dev.bukkit.org/server-mods/clearlagg/

**Comment by soulgriever** [comment] 2013-01-07 05:31
as far as coreprotect I will test that out later as I love cp and I will post error logs if it doesnt work, as far as nolagg, take my advice and RUN AWAY FROM IT, nolagg is the worst plugin you can use and it creates more problems then it fixes, clearlag is confirmed to work beautifuly I tried it earlier

**Comment by soulgriever** [comment] 2013-01-07 06:00
coreprotect wont run because it sees BukkitForge as an incompatable version of craftbukkit

2013-01-07 00:54:07 [INFO] [STDOUT] ------------------------------
2013-01-07 00:54:07 [INFO] [STDOUT] [CoreProtect] CoreProtect was unable to start.
2013-01-07 00:54:07 [INFO] [STDOUT] [CoreProtect] An incompatible Craftbukkit version was detected.
2013-01-07 00:54:07 [INFO] [STDOUT] ------------------------------
2013-01-07 00:54:07 [INFO] [net.coreprotect.CoreProtect] [CoreProtect] Disabling CoreProtect v1.74

**Comment by keepcalm** [comment] 2013-01-07 08:47
Fixed in latest build. Look at the config file ;)

**Closed as completed by keepcalm** 2013-01-07 08:47 UTC
