### ISSUE TITLE
Vanish No Packet not working.

### ISSUE THREAD

**Issue by gccruz** [keepcalm/BukkitForge#391] opened 2013-01-28 04:53 UTC
This plugin will not create a config file, nor will it allow any commands to work. It shows up in the Help menu. No error is outputed. 

http://dev.bukkit.org/server-mods/vanish/

**Comment by Bucky420** [comment] 2013-01-28 05:19
true .. thoe i use sworn patrol

**Comment by gccruz** [comment] 2013-01-28 06:39
How well does it work? I see its abandoned.

**Comment by SpoonsJTD** [comment] 2013-02-27 21:12
Dupe of #330. Until version check is disabled, nothing we can do.

**Closed as completed by SpoonsJTD** 2013-02-27 21:12 UTC
