### ISSUE TITLE
[worldedit] stops working

### ISSUE THREAD

**Issue by Tampa** [keepcalm/BukkitForge#102] opened 2013-01-04 01:20 UTC
I'm litterally sitting next to my friend here and we are both playing on the server i made, his worldedit is working fine, mine is gone. The Axe nor the Compass are doing what they are suppose to do. The weird thing is, it is not giving me an error in the console. I connected a couple times, but no errors and the startup is also clean. Running build 42 with the ported worldedit and no other plugins.

**Comment by SpiritedDusty** [comment] 2013-01-04 03:58
This exact same thing is happening to me too! I'm glad I'm not the only one that has this problem. I can't use my wand but my friend can.

**Comment by keepcalm** [comment] 2013-01-04 06:20
Check your permissions? Remove any perms plugins you have?

**Comment by Tampa** [comment] 2013-01-04 22:14
I'm op and there is no other plugin besides WE.

**Comment by keepcalm** [comment] 2013-01-04 22:27
Can you do //pos1 and //pos2?

**Comment by Tampa** [comment] 2013-01-05 02:36
returns null. I'm testing with build 50 atm, haven't been able to recreate the issue as of now. I found new issues tho, buttons are misbehaving for some reason, ill check if its mod related first.

**Comment by Tampa** [comment] 2013-01-06 01:05
With 53 its still happening, it seems its hooked on the time. If the server has been running for a certain amount hours WE shuts down.

**Comment by keepcalm** [comment] 2013-01-06 05:44
Weird.

**Comment by Tampa** [comment] 2013-01-06 21:32
It's either BukkitForge that gets a hiccup after some time without shouting errors or its your WE Port. I will keep updating BF and see, if anything changes. If it turns out to be the WE Port i guess thats no biggy, but if it is really BF then there is some serious issue waiting to blow up. Could you build in some more debug code to write everything BF does to console, so i can check the logs for the reason?

**Comment by keepcalm** [comment] 2013-01-06 23:07
Ok.

**Comment by Listy** [comment] 2013-01-20 15:40
I think I'm getting the same error - I've only just created the tekkit lite server (build 60) and used the version of worldedit linked to from your page.  There are only worldguard and worldedit running - No permissionsEX installed yet, but I am OP on the server.

 When I first log on it all appears to be working ok...wand command works and when I left click it sets 1st coord and tells me, and then right click sets 2nd pos and it tells me so.   Then when I log out and then back in again, the wand doesn't work as expected - Left and Right clicking produces no on-screen acknowledgement that anything has happened...no nice little purple writing at all. :(

The positions must actually be being set though (just not displaying anything) because if I then type //set 0 for instance after setting two positions, it does indeed set them to block 0 for that area.

At first I was unsure if this was a problem with BukkitForge, the WE version, or the WorldEditCUI I'd just put back on my client - but a clean install of the client produces the same result.

If I restart the server and log in then everything is ok.... I can recreate the problem easily though by logging out and then back in again - and it's broken.

hope the info helps...

Listy

**Comment by mmis1000** [comment] 2013-01-21 11:34
fixed in # 75 in new build server

**Comment by SpoonsJTD** [comment] 2013-01-21 17:37
Listy or Tampa, can you check current build version? An update was made that should address the 'works until I reconnect' issues.

**Comment by Listy** [comment] 2013-01-22 17:32
Thanks Spoons, I'll check later when I get back home and post the results.

**Comment by Listy** [comment] 2013-01-22 18:22
Spoons, just tested build 90 and I can confirm I'm no longer experiencing the problem.   Thanks.

**Closed as completed** 2013-01-22 21:16 UTC
Labels: status - confirmed bug
