### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by Wolftein** [keepcalm/BukkitForge#81] opened 2013-01-02 01:49 UTC
When i hit something with the wand it won't work, also hpos1, hpos2, gives null for that reason i can't make a region and i won't be able to test futher commands

**Comment by Manawyrm** [comment] 2013-01-02 02:54
We have just fixed the bug with marking a region.
But theres still something left...

**Comment by Tampa** [comment] 2013-01-02 03:00
In BukkitForge or in the WE Port?

**Comment by minecrafter** [comment] 2013-01-02 03:00
Duplicate of #29.

**Comment by Manawyrm** [comment] 2013-01-02 03:01
in BukkitForge. Btw: VoxelSniper does work fine now ;)

**Comment by Wolftein** [comment] 2013-01-02 04:40
hpos isn't fixed and when i select the region and do a command it says: Make a region selection first :P

**Comment by keepcalm** [comment] 2013-01-02 04:51
yes, I know, I'm working on it... It's pretty hard to track down.

**Comment by Wolftein** [comment] 2013-01-02 04:51
You're doing a great job @keepcalm :)

**Comment by keepcalm** [comment] 2013-01-02 05:09
thanks

**Comment by keepcalm** [comment] 2013-01-02 07:27
Hey, guess what? WORLDEDIT works! Thanks @Manawyrm :D

**Closed as completed by keepcalm** 2013-01-02 07:27 UTC
