### ISSUE TITLE
Crashing when gen a world for first time 

### ISSUE THREAD

**Issue by void513** [keepcalm/BukkitForge#477] opened 2013-02-09 02:49 UTC
I am running the on a Feed the Beast  Direwolf20  serverwith the
BukkitForge-1.4.7-227

2013-02-08 21:42:32 [INFO] Starting minecraft server version 1.4.7
2013-02-08 21:42:54 [INFO] Loading properties
2013-02-08 21:42:54 [INFO] Default game type: SURVIVAL
2013-02-08 21:42:54 [INFO] Generating keypair
2013-02-08 21:42:55 [INFO] Starting Minecraft server on _:25565
2013-02-08 21:42:55 [WARNING] *_*\* SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
2013-02-08 21:42:55 [WARNING] The server will make no attempt to authenticate usernames. Beware.
2013-02-08 21:42:55 [WARNING] While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
2013-02-08 21:42:55 [WARNING] To change this, set "online-mode" to "true" in the server.properties file.
2013-02-08 21:43:04 [INFO] Preparing level "world"
2013-02-08 21:43:19 [INFO] Preparing start region for level 0
2013-02-08 21:43:19 [SEVERE] Encountered an unexpected exception NullPointerException
java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:70)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkPopulateEvent.<init>(ChunkPopulateEvent.java:16)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.populateChunks(ForgeEventHandler.java:925)
    at net.minecraftforge.event.ASMEventHandler_129_ForgeEventHandler_populateChunks_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at abb.a(ChunkProviderGenerate.java:601)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1258)
    at im.c(ChunkProviderServer.java:153)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:310)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)
2013-02-08 21:43:20 [SEVERE] This crash report has been saved to: C:\DireWolf Server.\crash-reports\crash-2013-02-08_21.43.20-server.txt

**Comment by void513** [comment] 2013-02-09 02:54
here the crash log 

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2/8/13 9:43 PM
Description: Exception in server tick loop

java.lang.NullPointerException
    at org.bukkit.craftbukkit.CraftChunk.getWorld(CraftChunk.java:70)
    at org.bukkit.event.world.ChunkEvent.<init>(ChunkEvent.java:12)
    at org.bukkit.event.world.ChunkPopulateEvent.<init>(ChunkPopulateEvent.java:16)
    at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.populateChunks(ForgeEventHandler.java:925)
    at net.minecraftforge.event.ASMEventHandler_129_ForgeEventHandler_populateChunks_Post.invoke(.dynamic)
    at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
    at net.minecraftforge.event.EventBus.post(EventBus.java:103)
    at abb.a(ChunkProviderGenerate.java:601)
    at im.a(ChunkProviderServer.java:258)
    at zz.a(Chunk.java:1258)
    at im.c(ChunkProviderServer.java:153)
    at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:310)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
    at ho.c(DedicatedServer.java:180)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:458)
    at fy.run(SourceFile:849)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.7
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_13, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 287709848 bytes (274 MB) / 671023104 bytes (639 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -Xms512M -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
    FML: MCP v7.26a FML v4.7.22.539 Minecraft Forge 6.6.0.515 61 mods loaded, 61 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CodeChickenCore [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    NotEnoughItems [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TreeCapitator [TreeCapitator]([1.4.6]TreeCapitator.Forge.1.4.6.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge [BukkitForge](BukkitForge-1.4.7-227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BlockBreak [Block Break Event](BukkitForge-1.4.7-227.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Core [BuildCraft](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Builders [BC Builders](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Energy [BC Energy](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Factory [BC Factory](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Transport [BC Transport](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BuildCraft|Silicon [BC Silicon](buildcraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ComputerCraft [ComputerCraft](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CCTurtle [ComputerCraft Turtles](computercraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion [Thermal Expansion](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    OmniTools [OmniTools](omnitools.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2 [IndustrialCraft 2](ic2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ChargePads [Charge Pads](chargepads.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ChickenChunks [ChickenChunks](chickenchunks.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    CompactSolars [Compact Solar Arrays](compactsolars.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EE3 [Equivalent Exchange 3](ee3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    EnderStorage [EnderStorage](enderstorage.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtrabiomesXL [ExtrabiomesXL](extrabiomesxl.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forestry [Forestry for Minecraft](forestry.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BinnieCore [Binnie Core](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ExtraBees [Extra Bees](extrabees.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    factorization [Factorization](factorization.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraviGun [GraviGun](gravigun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    GraviSuite [Gravitation Suite](gravisuite.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IC2NuclearControl [Nuclear Control](ic2nuclearcontrol.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    IronChest [Iron Chest](ironchest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    MiscPeripherals [MiscPeripherals](miscperipherals.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ModularForceFieldSystem [Modular ForceField System V2](modularforcefieldsystem.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Mystcraft [Mystcraft](mystcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ObsidiPlates [Obsidian Pressure Plates](obsidiplates.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    PortalGun [Portal Gun](portalgun.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Railcraft [Railcraft](railcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCore [RedPower](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerBase [RP Base](redpowercore.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerMachine [RP Machine](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerCompat [RP Compat](redpowercompat.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWiring [RP Wiring](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLogic [RP Logic](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerLighting [RP Lighting](redpowerdigital.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerWorld [RP World](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    RedPowerControl [RP Control](redpowermechanical.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    SecretRoomsMod [The SecretRoomsMod](SecretRoomsMod-universal-4.4.1.158.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    SoulShards [SoulShards](soulshards.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    StevesCarts [Steve's Carts](stevescarts.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Thaumcraft [Thaumcraft](Thaumcraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Factory [Factory](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Energy [Energy](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|NEI [NEI](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    ThermalExpansion|Transport [Transport](thermalexpansion.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    TwilightForest [The Twilight Forest](twilightforest.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Core [WR-CBE Core](wirelessredstonecore.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|Addons [WR-CBE Addons](wirelessredstoneaddons.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    WR-CBE|RedPower [WR-CBE RedPower](wirelessredstoneredpower.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    XyCraft [XyCraft](xycraft.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BukkitForge Details: BukkitForge null-null (with bukkit API version 1.4.7-R0.1)
Plugins Loaded:[Didn't get far enough to load plugins :/]
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by jesusthekiller** [comment] 2013-02-09 20:05
Dupe of #475

**Closed as completed** 2013-02-28 02:33 UTC
